### ISSUE TITLE
solar_analytics.yaml configuration invalid!

### ISSUE THREAD

**Issue by samhegarty** [PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring#16]
Numerous errors in solar_analytics.yaml where checking configuration is saying configuration invalid. This includes spaces throughout the code. Once fixed, am stuck on expected '<document start>', but found '<scalar>' in '/config/solar_analytics/yaml", line 2155, column 15

**Comment by PeterH24x7** [comment]
Hi @samhegarty - sorry to read about your difficulties. I'm not sure I understand the 'space' issue or the matter on line 2155. Can you explain a bit more about what your doing (new install or upgrade) and which version of solar_analytics.yaml you are using. Happy to have an online chat and screen-share if that's easiest.
Chrs, Peter

**Comment by PeterH24x7** [comment]
Hi @samhegarty  - any further details on this issue? If not, I'll otherwise presume it's okay to close in 4 days time (Wed) if there's nothing else to be discussed. 
Chrs, Peter

**Comment by samhegarty** [comment]
Hi Peter

Thanks for checking. I looked at it in detail and my text editor added a
whole lot of random formatting which was the issue. I’ve now got it to work
so bug finished. Great stuff by the way!

Thanks, Sam

**Comment by PeterH24x7** [comment]
Hi Sam -- No problems - I'll close this issue as no fault found and glad it's useful to you. If you are otherwise interested in the latest code see the draft for testing in the following discussion - no further changes are expected at this time and a new release 6 should be published in the next week.
https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/discussions/15. 
Chrs, Peter
