### ISSUE TITLE
Unsupported state class - sensor.sa_todays_energy_generated_expected_total

### ISSUE THREAD

**Issue by Roving-Ronin** [PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring#19]
Hi @PeterH24x7,

Running the latest 3p version (since released), just seen this pop up:

![image](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/108674933/d34cd020-531a-4cd2-8599-5bfae15dc8f4)

![image](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/108674933/554cbef1-2bd0-448d-8630-5487a9745b55)

**Comment by PeterH24x7** [comment]
Hi @Roving-Ronin - just back from holidays. This is a strange one as the state_class is "total" and also used by other sensors. I've not done any updates over the last month so not seen the error myself. I will investigate further over the weekend, time permitting. Let me know if you have any ideas in the mean time. 
Chrs, Peter

**Comment by PeterH24x7** [comment]
@Roving-Ronin - I need some help. Where does the "Statistics ID" etc image come from?

**Comment by Roving-Ronin** [comment]
@PeterH24x7 that's just the ... Developer Tools ---> Statistics screen, where you can see all your sensors that have issues etc.
FYI I updated that sensor to use total_increasing, given the description at:

https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes

![image](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/108674933/a735ee27-e26f-4b96-9ae7-628c62e9f526)

Only been going 80min, and just did a reload configuration to see if it then resets to zero, but so far its tracking correctly and updating to show the expected total today / recorder is working with no error messages.

PS. Some of the wording on the HA sensors doco is a bit of 'read it 10 times and scratch the head', as to how its supposed to work

**Comment by PeterH24x7** [comment]
Hi @Roving-Ronin - I've updated my development HA system and get the same issue after the recent upgrade. Yes very familiar with the table above. The reason **sa_todays_energy_generated_expected_total** is "**total**", and not "**total_increasing**" like other related sensors (e.g. **sa_todays_energy_consumed_solar**), is because the generated forecast can change upwards and downwards so **total_increasing** generated problems in the system logs. It nonetheless fits the definition of "total". I don't understand why it's suddenly an issue to be honest. I'm a little suspect of the issue message "**The state class '' of this entity is not supported.**" where there's nothing inside the single-quotes. Is it possible the yaml interpreter is being tricked by some formatting glitch/error in the yaml code?

**Comment by PeterH24x7** [comment]
Hi @Roving-Ronin - just checking if you are still experiencing the issue? Having done the update on my dev system, the issue appears to have rectified itself.

![image](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/91523850/72faaf32-9ee2-483b-a8e4-d5b8f24e7491)

**Comment by Roving-Ronin** [comment]
@PeterH24x7 

Sorry left this to keep an eye upon and then forgot about it.
Since doo g that change, no it's been Ok.
I later had a few other sensors do exactly the same thing and solved by changing the state class. Think it must have been a recent change in HA that caused it and forces everyone to change the state class.

**Comment by PeterH24x7** [comment]
Hi @Roving-Ronin - I remain unconvinced that there's a real problem and having reviewed and re-reviewed the **state_class** documentation over and over again I don't understand why **total** wouldn't apply (any longer). Otherwise on my development system there remain zero issues, and I've recently upgraded my production HA to 2024.4.4 - again no issues in the developer tools > statistics (see emage below). Lastly the fact that the issue description seemed incomplete suggests to me there's something else is not maybe working as it should. Any chance you can switch back the state classes and see if the matter returns? I'm otherwise inclined to close this thread in the absence of greater certainty, clarity or support. Chrs, Peter

![image](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/91523850/e34680f2-78ff-4541-ba77-6b962fecaf34)

**Comment by PeterH24x7** [comment]
@Roving-Ronin  - here's a possibility. Does the **state_class** issue occur when the sensor is unavailable (at start-up)? So once the sensor has a numeric value, the issue goes away as the value is compatible with the **state_class total**.

**Comment by PeterH24x7** [comment]
No fault found. Presumed to be a start-up issue that resolves itself.
